# Generated by Django 5.2.5 on 2025-08-24 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GISapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dts', to='GISapp.feeder')),
            ],
        ),
    ]
