# Generated by Django 5.2.5 on 2025-08-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GISapp', '0002_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='dt',
            name='capacity',
            field=models.CharField(choices=[('25', '25 kVA'), ('63', '63 kVA'), ('100', '100 kVA'), ('160', '160 kVA'), ('250', '250 kVA'), ('315', '315 kVA'), ('500', '500 kVA')], default='400', max_length=10),
        ),
    ]
