# Generated by Django 5.2.5 on 2025-08-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GISapp', '0004_alter_dt_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
