# Generated by Django 5.2.5 on 2025-08-24 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GISapp', '0005_locationentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeederDTSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_point_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_point_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_point_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GISapp.dt')),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GISapp.feeder')),
            ],
        ),
    ]
